language: bash

sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'
 - pip install --user bashate

matrix:
  fast_finish: true
