language: bash

sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

install:
 - pip install --user bashate

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'
 - bash -c 'shopt -s globstar; bashate **/*.sh'

matrix:
  fast_finish: true
