language: bash

sudo: required

addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
    - udftools
    - coreutils
    - vim-common

install:
 - pip install --user bashate

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'
 - bash -c 'shopt -s globstar; bashate **/*.sh'
 - ./format-udf.sh -v
 - ./format-udf.sh -h
 - ./unit-test.sh

matrix:
  fast_finish: true
