language: bash

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y udftools coreutils vim-common
  - curl https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo apt-key add -
  - echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install shellcheck -y

install:
 - pip install --user bashate

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'
 - bash -c 'shopt -s globstar; bashate **/*.sh'
 - ./format-udf.sh -v
 - ./format-udf.sh -h
 - ./unit-test.sh

matrix:
  fast_finish: true
